name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Use the latest version of the software
        - Provide as much detail as possible

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Set environment variable '...'
        2. Run command '....'
        3. Send request to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected the server to...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, the server...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of dynapins-server are you running?
      placeholder: "v0.2.0"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running the server?
      options:
        - Docker
        - Kubernetes
        - Local (go run)
        - Binary
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go? (if running locally)
      placeholder: "go1.25.3"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant environment variables (⚠️ DO NOT include private keys!)
      placeholder: |
        PORT=8080
        ALLOWED_DOMAINS="example.com"
        SIGNATURE_LIFETIME="1h"
        LOG_LEVEL="debug"
      render: bash
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (⚠️ DO NOT include sensitive data!)
      placeholder: Paste logs here
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, network traces, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I am using the latest version
          required: true
        - label: I have removed all sensitive information from this report
          required: true
