apiVersion: v1
kind: Secret
metadata:
  name: dynapins-key
  namespace: default
type: Opaque
stringData:
  # Replace with your actual ECDSA P-256 private key
  # Generate with: openssl ecparam -genkey -name prime256v1 -noout -out private_key.pem
  private_key.pem: |
    -----BEGIN PRIVATE KEY-----
    YOUR_PRIVATE_KEY_HERE
    -----END PRIVATE KEY-----



