apiVersion: v1
kind: Service
metadata:
  name: dynapins-server
  namespace: default
  labels:
    app: dynapins-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: dynapins-server



